version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: on-failure
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
  web:
    build: .
    restart: on-failure
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
    command: "node tutorial.js"
    network_mode: "host"

